create table accounts (account_id bigint generated by default as identity, iban varchar(255), account_number varchar(255), account_type varchar(255), balance double, currency varchar(255), user_id bigint not null, primary key (account_id));
create table statement (statement_id bigint generated by default as identity, account_number varchar(255), amount double, description varchar(255), transaction_date timestamp, account_id bigint not null,user_id bigint not null, primary key (statement_id));
create table users (user_id bigint generated by default as identity, first_name varchar(255), last_name varchar(255), user_name varchar(255),pword varchar(255), role varchar(255), logged_in boolean not null, primary key (user_id));
alter table accounts add constraint UKm507upg2gtg1crodqaw55oegd unique (account_number);
alter table users add constraint UKmmns67o5v4bfippoqitu4v3t6 unique (user_name);
alter table accounts add constraint FKnjuop33mo69pd79ctplkck40n foreign key (user_id) references users;
alter table statement add constraint FK25jt3htebne22lg411s9ef8mh foreign key (account_id) references accounts;
